# Generated by Django 4.1.1 on 2022-11-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allposts',
            fields=[
                ('post_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=10, null=True)),
                ('text', models.CharField(max_length=100, null=True)),
                ('topic', models.CharField(max_length=10, null=True)),
                ('image', models.ImageField(upload_to=None)),
                ('timeadded', models.DateTimeField(auto_now_add=True)),
                ('public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=10, null=True)),
                ('followers', models.CharField(max_length=500, null=True)),
                ('following', models.CharField(max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Postcomments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=10, null=True)),
                ('comment', models.CharField(max_length=100, null=True)),
                ('user', models.CharField(max_length=10, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Postlikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=10, null=True)),
                ('user', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=10, null=True)),
                ('interest', models.CharField(max_length=300, null=True)),
                ('public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Unfpenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=10, null=True)),
                ('unfollow', models.CharField(max_length=10, null=True)),
                ('time', models.DateTimeField(null=True)),
            ],
        ),
    ]
