# Generated by Django 4.1.1 on 2022-11-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channeldet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default=0, max_length=10)),
                ('chname', models.CharField(default=0, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='upallvideo',
            fields=[
                ('vid', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.CharField(default=0, max_length=10)),
                ('chname', models.CharField(default=0, max_length=20)),
                ('titlle', models.CharField(default=0, max_length=100)),
                ('details', models.CharField(default=0, max_length=2000)),
                ('video', models.FileField(upload_to=None)),
                ('thumb', models.ImageField(upload_to=None)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='videocom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.CharField(default=0, max_length=10)),
                ('user', models.CharField(default=0, max_length=10)),
                ('comment', models.CharField(default=0, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='videolikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.CharField(default=0, max_length=10)),
                ('user', models.CharField(default=0, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='videoview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.CharField(default=0, max_length=10)),
                ('user', models.CharField(default=0, max_length=10)),
            ],
        ),
    ]
